name: estocks_app
description: App de controle de estoque almoxarifado
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ BANCO LOCAL
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ðŸ”” NOTIFICAÃ‡Ã•ES
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # ðŸ†” GERADOR DE ID
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # ðŸ”¥ GERADOR DO HIVE
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
